### ISSUE TITLE
Tableau Graph design pre-data

### ISSUE THREAD

**Issue by JacobbMorton** [HappyM0f0/ClassProject2022#11]
get a list of graphs we want to make with the cleaned data once ready

**Comment by kartsri** [comment]
Added visualizations.

[Map Visualization: Bucket is Color, Business Score is Size.](https://public.tableau.com/app/profile/kartik.sridhar/viz/CLIBucketandBizScoreMap/CostofLivingBucketMap?publish=yes)

[Clustered Column: Business Score and Quantity Score](https://public.tableau.com/app/profile/kartik.sridhar/viz/BizandQuantScorebyBucket/BusinessandQuantityScoresbyBucket?publish=yes)

**Comment by kartsri** [comment]
@JacobbMorton Closing this one out! Ready to embed if we like the visualizations. Let me know if you guys have feedback/edits @tpatel0107 @HappyM0f0 -- I know we liked the idea of a map when we were meeting last.

**Comment by tpatel0107** [comment]
Map idea works for me. I will review the project details tonight for any
updates

**Comment by kartsri** [comment]
Updated map visualization @JacobbMorton 

https://public.tableau.com/app/profile/kartik.sridhar/viz/CLIandBusinessScoreMap/CityStartupMap?publish=yes
